services:

  app:
    build: .
    container_name: ecommerce_api

    ports:
      - "4000:4000"

    env_file:
      - .env

    environment:
      MONGO_URI: mongodb://mongo:27017/ecommerce

    depends_on:
      mongo:
        condition: service_healthy

    volumes:
      - ./uploads:/app/uploads

    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: ecommerce_mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  mongo_data: